### PR TITLE
Patch lwm2m_obj_firmware_pull w/ URI parser

### PR DESCRIPTION
**Pull request by rbtchc**
Hi Mike,
I've patched lwm2m_obj_firmware_pull w/ http parser.
It's leveraged on http parser that has already been implmeneted before in Zephyr codebase.
Please feel free to fold them into your patch if it looks okay to you.

### CODE REVIEW

**Review by mike-scott — COMMENTED** [review]
I pulled the compiler fix into my PR for mainline Zephyr.  And I love the change to using HTTP parser for firmware pull.  That was only my list of things to do.  I'd like to get this submitted upstream once the main LWM2M PRs are merged.    In general, the client needs to parse the security URIs using a similar approach and start the RD client based on the data in index 0.  Instead of having the sample app set the remote addr directly.

**Comment by rbtchc** [comment]
Agree. I guess we need to initiate network connection at lwm2m_rd_client.c so that each time security uri is changed (bootstrapped) we can adjust the client accordingly.

BTW, I check the net_app api, it seems already taken care of DNS lookup and DTLS.

**Comment by rbtchc** [comment]
Hi Mike,

Besides adding the firmware uri parser in the earlier commit, I also add the state machine for handling the firmware update.
There are some issues that I'd like to discuss about.
1. It's not easy for the object instance callback function to return response code directly to the client.
    The lwm2m_engine seems interprete the error code returned from the callback function to the response code. If it's an unhandled error code (other than ENOMEN and EPERM), it will be treated as 500 (internal error).
1. The Size1/2 option is not always available (RFC7959 mentioned that we shouldn't expect it's there). Therefore, we should considered "total_size" as an unknown value and the callback function should be tweaked to handle that.
1. Because we have to handle the update state / update result. I think we shouldn't pass the data to application callback directly. 

Robert

**Comment by rbtchc** [comment]
Hi Mike,

I've add back the firmware push support based on your latest version of lwm2m. Please take a look and let me know if you have any question.

Robert

**Comment by mike-scott** [comment]
Hi @rbtchc 
I think we're close to the upstream LwM2M library getting merged which means that we can focus on getting patches like yours ready for upstream as well.  Let me take a look.

Thank you for being patient while we take care of this stuff :)

- Mike

**Comment by rbtchc** [comment]
Sure thing. I'm expecting to wait for them to be merged into the upstream and then submit mine to zephyr project, too  :)

**Pull request closed without merging**
